---EXTERNAL DATA SOURCE CREATION

CREATE EXTERNAL DATA SOURCE ADVENTURE_WORKS_DS WITH (
    LOCATION = 'https://advworksrb.blob.core.windows.net/gold',
    CREDENTIAL = CRED_ADVENTURE_WORKS
)

---EXTERNAL FILE FORMAT CREATION
CREATE EXTERNAL FILE FORMAT ADVENTURE_WORKS_FF WITH (
    FORMAT_TYPE = PARQUET,
    DATA_COMPRESSION = 'org.apache.hadoop.io.compress.GzipCodec'
)
GO

---EXTERNAL TABLE CREATION WITH CETAS

 CREATE EXTERNAL TABLE GOLD.SALES WITH(
    LOCATION = 'Sales/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/Sales/',
    FORMAT = 'PARQUET'
) SALES
GO

CREATE EXTERNAL TABLE GOLD.CUSTOMERS WITH(
    LOCATION = 'Customers/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/Customers/',
    FORMAT = 'PARQUET'
) CUSTOMERS
GO

CREATE EXTERNAL TABLE GOLD.PRODUCTS WITH(
    LOCATION = 'Products/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/Products/',
    FORMAT = 'PARQUET'
) PRODUCTS
GO


CREATE EXTERNAL TABLE GOLD.RETURNS WITH(
    LOCATION = 'Returns/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/Returns/',
    FORMAT = 'PARQUET'
) RETURNS
GO

CREATE EXTERNAL TABLE GOLD.SUBCATEGORIES WITH(
    LOCATION = 'SubCategories/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/SubCategories/',
    FORMAT = 'PARQUET'
) SUBCATEGORIES
GO

CREATE EXTERNAL TABLE GOLD.CALENDAR WITH(
    LOCATION = 'Calendar/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/Calendar/',
    FORMAT = 'PARQUET'
) CALENDAR
GO

CREATE EXTERNAL TABLE GOLD.TERRITORIES WITH(
    LOCATION = 'Territories/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/Territories/',
    FORMAT = 'PARQUET'
) TERRITORIES
GO

CREATE EXTERNAL TABLE GOLD.CATEGORIES WITH(
    LOCATION = 'categories/',
    DATA_SOURCE = ADVENTURE_WORKS_DS,
    FILE_FORMAT = ADVENTURE_WORKS_FF

) AS 
SELECT * FROM OPENROWSET(
    BULK 'https://advworksrb.dfs.core.windows.net/silver/Categories/',
    FORMAT = 'PARQUET'
) CATEGORIES
GO



-- DROP EXTERNAL TABLE GOLD.;